---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8.3

inputs:
  - name: dp-dataset-exporter
    path: go/src/github.com/ONSdigital/dp-dataset-exporter

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-dataset-exporter/ci/scripts/build.sh