---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.2

inputs:
  - name: dp-dataset-exporter
    path: dp-dataset-exporter

outputs:
  - name: build

run:
  path: dp-dataset-exporter/ci/scripts/build.sh
